config/routes.rb
Rails.application.routes.draw do

  get 'group_projects/group_projects'

  resources :resources
  resources :topics do
    member do
      post 'upvote'
    end
  end

  get 'resources/index' => 'resources#index'
  get 'topics/index' => 'topics#index'
  root 'about#about'

  controller :about do
    get :about
  end

  controller :members do
    get :members
  end

end

app/models/resource.rb
class Resource < ActiveRecord::Base
	validates :name, presence: true,

       length: { minimum: 2 }
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :votes, dependent: :destroy

  validates :title, presence: true,
                    length: { minimum: 2 }

  scope :topic_type, -> (topic_type) { where topic_type: topic_type}
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :topic
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def about
  	end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/group_projects_controller.rb
class GroupProjectsController < ApplicationController
  def group_projects
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	def members
  end  
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
	def index
		@resources = Resource.all
	end

	def show
    	@resource = Resource.find(params[:id])
  	end

	def new
		@resource = Resource.new 
	end

	def edit
	  @resource = Resource.find(params[:id]) 
	end

	def create
		if params[:content].present? # honeypot check
			@resource = ""
		else
			@resource = Resource.new(resource_params) 
		end
		if (!@resource.blank?)
  			if @resource.save
  				redirect_to @resource
  			else
    			render 'new'
  			end
		else
			redirect_to resources_path
  		end
  	end

  	def update
	  	if params[:content].present? # honeypot check
			@resource = ""
		else
			@resource = Resource.find(params[:id])
		end
 		if (!@resource.blank?)
	  		if @resource.update(resource_params)
	    		redirect_to @resource
	  		else
	    		render 'edit'
	  		end
  		else
			redirect_to resources_path
	  	end
	end

	def destroy
	  @resource = Resource.find(params[:id])
	  @resource.destroy
	 
	  redirect_to resources_path
	end	

  	private
  		def resource_params
    		params.require(:resource).permit(:name, :resource_type, :external_link, :description, :category, :content)
  		end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	def index
		if params[:topic_type] == 'Lightning Talk'
			@topics = Topic.topic_type('Lightning Talk')
		elsif params[:topic_type] == 'Large Demo'
			@topics = Topic.topic_type('Large Demo')
		else
			@topics = Topic.all.sort_by { |topic| topic.votes.count }.reverse!
		end
  	end

  	def show
  		@topic = Topic.find(params[:id])
  	end

  	def new
  		@topic = Topic.new
	end

	def edit
		@topic = Topic.find(params[:id])
	end

  	def create
  		if params[:content].present? # honeypot check
			@resource = ""
		else
			@topic = Topic.new(topic_params)
		end
		if(!@topic.blank?)
  			if @topic.save
  				redirect_to @topic
  			else 
  				render 'new'
  			end
  		else
  			redirect_to(topics_path)
  		end
	end

	def update
		if params[:content].present? # honeypot check
			@resource = ""
		else
			@topic = Topic.find(params[:id])
		end
	 	
	 	if(!@topic.blank?)
	  		if @topic.update(topic_params)
	  			redirect_to @topic
	  		else
	    		render 'edit'
	  		end
  		else
  			redirect_to(topics_path)
  		end
	end

	def destroy
		@topic = Topic.find(params[:id])
		@topic.destroy
		 
		redirect_to topics_path
	end

	def upvote
		@topic = Topic.find(params[:id])
		@topic.votes.create
		redirect_to(topics_path)
	end

	private
		def topic_params
			params.require(:topic).permit(:title, :description, :topic_type)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_projects_helper.rb
module GroupProjectsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/about/about.html.erb
<div class="row">
  <div class="jumbotron about">
    <div class="title">
      <h2 class="col-xs-10 col-xs-offset-1">"We believe in the pursuit of learning and creating a better life for ourselves. Learning to code is a great investment of your time and energy. Sometimes continuing to grow means you learn from others, and sometimes it means to teach them."</h2>
      <h4 class="col-xs-5 col-xs-offset-7">-Milwaukee Code Slingers</h4>
      <a href="#moreAbout">
        <i id="arrow" class="fa fa-angle-down fa-5x col-xs-2 col-xs-offset-6 arrow"></i>
      </a>
    </div>
  </div>

  <div id="moreAbout" class="name">
    <div class="text-center">
      <h1>We are the Milwaukee Code Slingers</h1>
    </div>
    <div class="col-xs-12 more-about">
      <div class="col-xs-5 col-xs-offset-1">
        <h2>Our Approach</h2>
        <p>By bringing together a group of aspiring, beginner, and intermediate developers, we can share ideas, ask questions and develop our skills. The format is structured. It involves time for topic-based learning, hands-on application for your projects and getting to know each other along with potential opportunities for projects and jobs. If you show up and are willing to put in the work, we will help you on your coding journey.</p>
      </div>
      <%= image_tag 'approach.JPG', class: 'col-xs-5' %>
    </div>
    <div class="col-xs-12 more-about">
      <%= image_tag 'meetup.JPG', class: 'col-xs-5 col-sm-offset-1' %>
      <div class="col-xs-5">
        <h2>Meet Up With Us!</h2>
        <p>Currently, we are focused upon beginner level topics for our meetups, simply due to the skill level of the members who were able to attend the first few meetups. In the future, we will have intermediate level topics as well.</p>
        <h5>We have 3 meetup types at the moment:</h5>
        <ol>
          <li>Big Topic Demo - A workshop of sorts - hands-on demo then time for application or group work after.</li>
          <li>Lightning Talks - 3-4 topics @ 5-7 min each, ANY member of ANY skill level can present. 2nd half is hands-on time.</li>
          <li>Shop Time - work on a group project, get help, pair program, share ideas or do some codewars.com!</li>
        </ol>
      </div>
    </div>
    <div class="col-xs-12 more-about">
      <div class="col-xs-5 col-xs-offset-1">
        <h2>Want To Share Your Knowledge?</h2>
        <p>If you are a more advanced, senior-level developer, consider being a mentor, presenting, or heading up a group project in a language of your choice. Any skill level can be a mentor for someone, you just have to have an open mind and a willingness to help your fellow Code Slingers...</p>
      </div>
      <%=	image_tag 'knowledge.JPG', class: 'col-xs-5' %>
    </div>
  </div>
</div>

app/views/group_projects/group_projects.html.erb
<h1>GroupProjects#group_projects</h1>
<p>Find me in app/views/group_projects/group_projects.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MKE Code Slingers</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Oxygen:400,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  </head>
  <body>
  	<nav class="navbar navbar-inverse navbar-static-top">
  		<div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--<a class="navbar-brand" <%= link_to 'MKE Code Slingers', root_path, :class => '' %></a>-->
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'About', root_path, :class => '' %></li>
              <li><%= link_to 'Members', members_path, :class => '' %></li>
              <li><%= link_to 'Resources', resources_path, :class => '' %></li>
              <li><%= link_to 'Topics', topics_path, :class => '' %></li>
            </ul>
          </div>
  		</div>
  	</nav>
    <%= yield %>
    <a class="up"><i class="fa fa-arrow-up fa-3x"></i></a>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  </body>
  <footer class="clearfix">
    <div class="container-fluid col-sm-12">
      <a href="http://milwaukeecodeslingers.org" class="copy-right">&copy;2016 MilwaukeeCodeSlingers</a>
      <a href="http://www.meetup.com/MKE-Code-Slingers/events/" class="GitHubIcon social">MeetUp</a>
      <a href="https://github.com/mkecodeslingers" class="MeetupIcon social"><i class="fa fa-github fa-2x"></i></a>
    </div>
  </footer>
</html>

app/views/members/members.html.erb
<div class="jumbotron intro members">
  <h1>Get to know <br> the code slingers!</h1>
  <h3>These are all of the awesome people you'll get to hangout with.</h3>
</div>
<div class="col-md-8 col-md-offset-2 member-pics">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" >
      
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <!--li data-target="#carousel-example-generic" data-slide-to="2"></li-->
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner inner" role="listbox">
        <div class="item member active">
          <%= image_tag "ed.jpg", class: 'member-image' %>
          <div class="carousel-caption" >
            <h1 >Ed Knueppel</h1>
          </div>
        </div>
        
        <div class="item member">
          <div class="carousel-caption">
            <h1 >Ryan Lijewski</h1>
          </div>
          <%= image_tag "ryan.jpg", class: 'member-image' %>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
  </div>
</div>

app/views/resources/_form.html.erb
<%= simple_form_for @resource do |f| %>
<% if @resource.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h5>
        <%= pluralize(@resource.errors.count, "error") %> prohibited
        this resource from being saved:
      </h5>
      <ul>
        <% @resource.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div>
    <form>
      <div class="form-group ">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.input :resource_type, collection: [:Website, :Blog, :Book, :PodCast, :Tutorial, :Documentation], class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :external_link %><br>
        <%= f.text_area :external_link, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: 'form-control' %>
      </div>

      <div class="form-group honeypot">
        <%= label_tag :content %>
        <%= text_field_tag :content, nil, tabindex: '-1' %>
        <span class="help">Do not fill in this field. It is an anti-spam measure.</span>
      </div>

      <div class="form-group">
        <%= f.input :category, collection: [:Development, :Design, :Testing, :Tools, :Data, :Serving, :Hosting, :Methodology], class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    </form>
</div>

<% end %>

app/views/resources/edit.html.erb
<div class="col-md-6 col-md-offset-3" style="padding-bottom: 70px">
	<h1>Editing Resource</h1>
	 
	<%= render 'form' %>
	 
	<%= link_to 'Back', resources_path, class: 'btn btn-primary' %>
</div>

app/views/resources/index.html.erb
<div>
  <div class="jumbotron intro resources">
    <h1>Welcome to our <br> temple of knowledge!</h1>
    <h3>This is where we share all of our favorite tutorials, guides, and resources.</h3>
  </div>

  <div class="search-sort container-row row">
    <div class="add-new-item">
      <%= link_to 'Add a new resource!', new_resource_path, class: 'btn btn-info add-new' %>
    </div>
    <div class="form-group search-item">
      <input type="text" class="form-control" placeholder="Search resources">
    </div>
  </div>

  <div class="resource-container">
    <% @resources.each do |resource| %>
        <div class="booyah-box">
          <div class="resource-card">
            <h4><%= resource.category%></h4>
            <div class="resource-card-title">
              <a href="<%= resource_path(resource) %>"><h3><%= resource.name %></h3></a>
              <p><%= resource.description %></p>
            </div>
            <div class="resource-footer">
              <a href="<%= resource.external_link %>>"><%= resource.external_link %></a>
              <%= resource.resource_type %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/resources/new.html.erb
<div class="col-md-6 col-md-offset-3" style="padding-bottom: 70px">
	<h1>New Resource</h1>
		
	<%= render 'form' %>

	<%= link_to 'Back', resources_path, class: 'btn btn-primary' %>
</div>

app/views/resources/show.html.erb
<div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @resource.name %></h3>
      </div>
      <div class="panel-body">
        <ul class="list-unstyled">
          <li>
            <strong>Resource Type:</strong>
            <br>
            <%= @resource.resource_type %>
          </li>
          <br>
          <li>
            <strong>External Link:</strong>
            <br>
            <%= @resource.external_link %>
          </li>
          <br>
          <li>
            <strong>Description:</strong>
            <br>
            <%= @resource.description %>
          </li>
          <br>
          <li>
            <strong>Category:</strong>
            <br>
            <%= @resource.category %>
          </li>
        </ul>
      </div>
    </div>

    <%= link_to 'Finish', resources_path, class: 'btn btn-success' %>
    <%= link_to 'Edit', edit_resource_path(@resource), class: 'btn btn-primary' %>
    <%= link_to 'Delete', resource_path(@resource), class: 'btn btn-danger',
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</div>

app/views/topics/_form.html.erb
<%= simple_form_for @topic do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h5>
        <%= pluralize(@topic.errors.count, "error") %> prohibited
        this topic from being saved:
      </h5>
      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <form>
      <div class="form-group ">
        <%= f.label :title %><br>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.input :topic_type, collection: [:'Lightning Talk', :'Large Demo'], class: 'form-control' %>
      </div>
     
      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      
      <div class="form-group honeypot">
        <%= label_tag :content %>
        <%= text_field_tag :content, nil, tabindex: '-1' %>
        <span class="help">Do not fill in this field. It is an anti-spam measure.</span>
      </div>      
     
      <div class="form-group">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    </form>
  </div>
<% end %>

app/views/topics/edit.html.erb
<div class="col-md-6 col-md-offset-3" style="padding-bottom: 70px">
	<h1>Editing Topic</h1>
		
	<%= render 'form' %>

	<%= link_to 'Back', topics_path, class: 'btn btn-primary' %>
</div>

app/views/topics/index.html.erb
<div>
  <div class="jumbotron intro topics">
    <h1>See what we'll <br> be getting into next!</h1>
    <h3>This is where we add and vote on topics we'll cover in our meetups.</h3>
  </div>

  <div class="search-sort row container-row">
    <div class="btn-group t-item" role="group">
      <button type="button" class="btn btn-info add-new">
        <%= link_to 'Show All', topics_path(:topic_type => 'All') %>
      </button>
      <button type="button" class="btn btn-info">
        <%= link_to 'Lightning Talks', topics_path(:topic_type => 'Lightning Talk') %>
      </button>
      <button type="button" class="btn btn-info add-new">
        <%= link_to 'Large Demo', topics_path(:topic_type => 'Large Demo') %>
      </button>
    </div>
    <div class="form-group t-item">
      <input type="text" class="form-control" placeholder="Search topics">
    </div>
    <div class="t-item">
      <%= link_to 'Add a new topic!', new_topic_path, class: 'btn btn-info add-new' %>
    </div>
  </div>

  <div class=" topic-container" >
    <% @topics.each do |topic| %>
        <div class="">
          <div class="booyah-box">
            <div class="container-fluid">
              <div class = "topic-card-header row">
                <div class="col-sm-3">
                  <h3 class="card"><%= topic.topic_type %></h3>
                </div>
                <div class="col-sm-5 col-sm-offset-2">
                  <h3 class="card"><%= pluralize(topic.votes.count, "Vote") %></h3>
                </div>
                <div class="col-sm-1 ">
                  <%= link_to 'Vote!', upvote_topic_path(topic), class: 'btn btn-info add-new',method: :post %>
                </div>
              </div>
                <div class="topic-card-title" >
                  <a href="<%= topic_path(topic) %>"><h3><%= topic.title %></h3></a>
                  <p class="truncate" ><%= topic.description %></p>
                </div>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="col-md-6 col-md-offset-3" style="padding-bottom: 70px">
	<h1>New Topic</h1>
		
	<%= render 'form' %>

	<%= link_to 'Back', topics_path, class: 'btn btn-primary' %>
</div>

app/views/topics/show.html.erb
<div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @topic.title %></h3>
      </div>
      <div class="panel-body">
        <ul class="list-unstyled">
          <li>
            <strong>Topic Type:</strong>
            <br>
            <%= @topic.topic_type %>
          </li>
          <br>
          <li>
            <strong>Description:</strong>
            <br>
            <%= @topic.description %>
          </li>
        </ul>
      </div>
    </div>

    <%= link_to 'Finish', topics_path, class: 'btn btn-success' %>
    <%= link_to 'Edit', edit_topic_path(@topic), class: 'btn btn-primary' %>
    <%= link_to 'Delete', topic_path(@topic), class: 'btn btn-danger',
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</div>